# SPDX-License-Identifier: LGPL-2.1-or-later
"""Professional PDF report generator — EMStudio's build-house deliverable pillar.

One document per analysis: title/summary, a construction or geometry drawing, result
curves, and a BOM / construction schedule — everything a parts house, wire
manufacturer, or fab supplier needs to build the design.

Built on matplotlib's PdfPages (no extra dependency; EMStudio already uses
matplotlib). Qt-free and FreeCAD-free so it runs headlessly and is unit-testable.
Two entry points today: ``litz_report`` (Litz Designer) and ``antenna_report``
(NEC2/openEMS sweeps); both share the page furniture so new analysis types slot in.
"""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg", force=False)
import numpy as np  # noqa: E402
from matplotlib.backends.backend_pdf import PdfPages  # noqa: E402
from matplotlib.figure import Figure  # noqa: E402
from matplotlib.patches import Circle as MplCircle  # noqa: E402
from matplotlib.patches import Rectangle as MplRect  # noqa: E402

PAGE = (8.27, 11.69)  # A4 portrait, inches
BRAND = "EMStudio"
# the disclaimer travels on every page of every report — these documents go to
# third parties (build houses, suppliers), so the notice must go with them
from emstudio.legal import SHORT_DISCLAIMER  # noqa: E402

FOOTER = ("Generated by EMStudio — open-source RF/EM engineering for FreeCAD\n"
          + SHORT_DISCLAIMER)


# --------------------------------------------------------------------- page parts
def _new_page():
    fig = Figure(figsize=PAGE)
    fig.subplots_adjust(left=0.08, right=0.92, top=0.92, bottom=0.06)
    return fig


def _header(fig, title, subtitle, page_no, page_total):
    fig.text(0.08, 0.965, BRAND, fontsize=16, fontweight="bold", color="#2b8cff")
    fig.text(0.08, 0.945, title, fontsize=12, fontweight="bold")
    if subtitle:
        fig.text(0.08, 0.928, subtitle, fontsize=9, color="#444444")
    fig.text(0.92, 0.965, "Page {0}/{1}".format(page_no, page_total),
             fontsize=8, ha="right", color="#888888")
    fig.text(0.5, 0.008, FOOTER, fontsize=6.5, ha="center", va="bottom",
             color="#999999")
    fig.patches.append(
        MplRect((0.08, 0.925), 0.84, 0.0015, transform=fig.transFigure,
                facecolor="#2b8cff", edgecolor="none")
    )


def _table(fig, rows, y0=0.88, x0=0.10, col_w=(0.40, 0.42), title=None, fontsize=9):
    """Draw a two-column key/value table; returns the y after the last row."""
    y = y0
    if title:
        fig.text(x0, y, title, fontsize=11, fontweight="bold")
        y -= 0.028
    for k, v in rows:
        fig.text(x0, y, str(k), fontsize=fontsize, color="#333333")
        fig.text(x0 + col_w[0], y, str(v), fontsize=fontsize, fontweight="bold")
        y -= 0.024
    return y


def _multicol_table(fig, headers, data_rows, y0, x0=0.10, width=0.82, fontsize=8,
                    col_frac=None):
    """Draw a bordered multi-column table (for BOM / schedules).

    ``col_frac`` optionally gives per-column width fractions (summing to ~1); the
    default is equal columns. Column x-positions are the cumulative offsets.
    """
    ncol = len(headers)
    if col_frac is None:
        col_frac = [1.0 / ncol] * ncol
    xs = [x0]
    for f in col_frac[:-1]:
        xs.append(xs[-1] + f * width)
    y = y0
    for j, h in enumerate(headers):
        fig.text(xs[j], y, str(h), fontsize=fontsize, fontweight="bold")
    y -= 0.006
    fig.patches.append(MplRect((x0, y), width, 0.001, transform=fig.transFigure,
                               facecolor="#333333", edgecolor="none"))
    y -= 0.020
    for row in data_rows:
        for j, cell in enumerate(row):
            fig.text(xs[j], y, str(cell), fontsize=fontsize)
        y -= 0.019
    return y


# --------------------------------------------------------------------- litz report
def _draw_cross_section(ax, construction):
    from emstudio.wire import cross_section

    data = cross_section.layout_arrays(construction)
    ax.set_aspect("equal")
    mm = 1e3
    from matplotlib.collections import EllipseCollection

    max_r = data["jacket_r"] or data["od_r"]
    if data["jacket_r"] > 0:
        ax.add_patch(MplCircle((0, 0), data["jacket_r"] * mm, facecolor="#4a4a55",
                               edgecolor="#222222", lw=1.2))
        ax.add_patch(MplCircle((0, 0), data["od_r"] * mm, facecolor="#f4f0e8",
                               edgecolor="#333333", lw=0.9))
    else:
        ax.add_patch(MplCircle((0, 0), data["od_r"] * mm, fill=False,
                               edgecolor="#333333", lw=1.2))

    def _coll(centers, radius, **kw):
        if len(centers) == 0:
            return
        d = 2.0 * radius * mm
        ax.add_collection(EllipseCollection(
            widths=[d] * len(centers), heights=[d] * len(centers), angles=0,
            units="xy", offsets=centers * mm, transOffset=ax.transData, **kw))

    for centers, r, _l in data["bundles"]:
        _coll(centers, r, facecolors="none", edgecolors="#2b8cff",
              linestyles="--", linewidths=0.7)
    core_pos, core_r = data["cores"]
    for (kx, ky), kr in zip(core_pos, core_r):
        ax.add_patch(MplCircle((kx * mm, ky * mm), kr * mm, facecolor="#eeeeee",
                               edgecolor="#888888", lw=0.6, hatch="...."))
    n = len(data["strands"])
    _coll(data["strands"], data["strand_r"], facecolors="#c87533",
          edgecolors=("#7a4418" if n <= 20000 else "none"),
          linewidths=(0.3 if n <= 20000 else 0.0))
    if data["profile"] is not None:
        hw, hh = data["profile"]
        ax.add_patch(MplRect((-hw * mm, -hh * mm), 2 * hw * mm, 2 * hh * mm,
                             fill=False, edgecolor="#ff5a5f", lw=1.2, linestyle="-."))
        max_r = max(max_r, hw)
    lim = max_r * mm * 1.1
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_xlabel("mm", fontsize=8)


def litz_report(construction, path, freq_min_hz=1e3, freq_max_hz=1e6,
                i_rms=None, h_ext_per_amp=0.0, project="", author=""):
    """Write a litz construction report PDF. Returns the path."""
    from emstudio.wire import litz as _l

    spec = construction.spec_dict()
    freqs = np.logspace(np.log10(freq_min_hz), np.log10(max(freq_max_hz, freq_min_hz * 2)), 200)
    fac = np.array([construction.ac_factor(f, h_ext_per_amp) for f in freqs])
    rac = np.array([construction.rac_per_meter(f, h_ext_per_amp) for f in freqs])

    with PdfPages(path) as pdf:
        # --- page 1: summary + cross-section ---
        fig = _new_page()
        _header(fig, "Litz Cable Construction Report", construction.name, 1, 2)
        rows = [
            ("Project", project or "—"),
            ("Prepared by", author or "—"),
            ("Litz type", "Type {0} — {1}".format(spec["litz_type"], spec["type_description"])),
            ("Strand", spec["strand_diameter"]),
            ("Total strands", spec["n_strands"]),
            ("Conductor OD", "{0:.3f} mm".format(spec["outer_diameter_mm"])),
            ("Finished OD (jacket)", "{0:.3f} mm".format(spec["finished_od_mm"])),
            ("Equivalent solid", "AWG {0}".format(spec["equivalent_awg"])),
            ("DC resistance", "{0:.3f} mΩ/m".format(spec["rdc_mohm_per_m"])),
            ("Copper weight", "{0:.2f} g/m".format(spec["copper_weight_g_per_m"])),
            ("Ampacity (DC, 30 K, still air)", "{0:.0f} A".format(spec["ampacity_dc_a"])),
        ]
        _table(fig, rows, y0=0.88, title="Summary")
        ax = fig.add_axes([0.10, 0.10, 0.80, 0.42])
        _draw_cross_section(ax, construction)
        ax.set_title("Cross-section (nominal — strands migrate along the lay)", fontsize=9)
        pdf.savefig(fig)

        # --- page 2: schedule + AC curves ---
        fig = _new_page()
        _header(fig, "Construction Schedule & AC Performance", construction.name, 2, 2)
        headers = ["Level", "Members", "Lay", "Dir", "Core", "Wrap", "OD after"]

        def _wrap_label(op):
            if not op["member_wrap"] or op["member_wrap"] == "—":
                return "—"
            short = op["member_wrap"].replace("polyester", "poly.").replace(" tape", " tp")
            if op["member_wrap_mm"] == 0:
                return short
            return "{0} {1:.2f}mm".format(short, op["member_wrap_mm"])

        data_rows = []
        for op in spec["operations"]:
            data_rows.append([
                op["level"], op["count"], "{0:.1f} mm".format(op["lay_mm"]),
                op["direction"],
                ("{0:.2f} mm".format(op["core_mm"]) if op["core_mm"] > 0 else "—"),
                _wrap_label(op),
                "{0:.2f} mm".format(op["od_after_mm"]),
            ])
        y = _multicol_table(fig, headers, data_rows, 0.86,
                            col_frac=(0.09, 0.13, 0.14, 0.08, 0.16, 0.24, 0.16))
        fig.text(0.10, y - 0.01, "Jacket: {0}".format(spec["jacket"]) + (
            ", {0:.2f} mm wall".format(spec["jacket_mm"]) if spec["jacket_mm"] > 0 else ""),
            fontsize=8)

        ax1 = fig.add_axes([0.12, 0.34, 0.78, 0.22])
        ax1.semilogx(freqs / 1e3, fac, "-", lw=2)
        ax1.set_ylabel("Rac / Rdc", fontsize=8)
        ax1.grid(True, which="both", alpha=0.4)
        ax1.set_title("AC resistance vs frequency", fontsize=9)
        ax2 = fig.add_axes([0.12, 0.09, 0.78, 0.20])
        ax2.loglog(freqs / 1e3, rac * 1e3, "-", lw=2)
        ax2.set_xlabel("Frequency (kHz)", fontsize=8)
        ax2.set_ylabel("Rac (mΩ/m)", fontsize=8)
        ax2.grid(True, which="both", alpha=0.4)
        pdf.savefig(fig)

        _set_metadata(pdf, "EMStudio Litz Report — " + construction.name, author)
    return path


# ------------------------------------------------------------------ antenna report
def antenna_report(result, path, title="Antenna Analysis", geometry_png=None,
                   bom_rows=None, project="", author=""):
    """Write an antenna/S-parameter report from a SweepResult. Returns the path."""
    f_min, s11_min = result.min_s11()
    with PdfPages(path) as pdf:
        fig = _new_page()
        _header(fig, title, result.meta.get("analysis", ""), 1, 2)
        rows = [
            ("Project", project or "—"),
            ("Prepared by", author or "—"),
            ("Solver", result.meta.get("backend", "—")),
            ("Port impedance", "{0:.0f} Ω".format(result.z0)),
            ("Best match", "{0:.2f} dB @ {1:.4f} GHz".format(s11_min, f_min / 1e9)),
            ("Min VSWR", "{0:.2f}".format(float(result.vswr().min()))),
        ]
        res = result.resonances()
        if res:
            rows.append(("Resonance(s)", ", ".join("{0:.3f} GHz".format(r / 1e9) for r in res[:3])))
        ff = getattr(result, "farfield", None)
        if ff is not None:
            g, th, _ = ff.peak()
            rows.append(("Peak gain", "{0:.2f} dBi @ θ={1:.0f}°".format(g, th)))
        _table(fig, rows, y0=0.88, title="Summary")

        ax = fig.add_axes([0.12, 0.36, 0.78, 0.20])
        ax.plot(result.freq / 1e9, result.s11_db(), "-", lw=2)
        ax.axhline(-10, ls="--", lw=1, color="#888888")
        ax.set_ylabel("S11 (dB)", fontsize=8)
        ax.set_xlabel("Frequency (GHz)", fontsize=8)
        ax.grid(True, alpha=0.4)
        ax.set_title("Reflection (S11)", fontsize=9)
        ax2 = fig.add_axes([0.12, 0.09, 0.78, 0.19])
        ax2.plot(result.freq / 1e9, np.real(result.zin), "-", lw=2, label="R")
        ax2.plot(result.freq / 1e9, np.imag(result.zin), "--", lw=2, label="X")
        ax2.axhline(0, lw=0.8, color="#888888")
        ax2.set_ylabel("Zin (Ω)", fontsize=8)
        ax2.set_xlabel("Frequency (GHz)", fontsize=8)
        ax2.grid(True, alpha=0.4)
        ax2.legend(fontsize=7)
        pdf.savefig(fig)

        # --- page 2: pattern + BOM ---
        fig = _new_page()
        _header(fig, title + " — Pattern & BOM", result.meta.get("analysis", ""), 2, 2)
        if ff is not None:
            ax = fig.add_axes([0.15, 0.45, 0.7, 0.45], projection="polar")
            for phi, style in ((0.0, "-"), (90.0, "--")):
                theta, gain = ff.cut(phi)
                ax.plot(np.deg2rad(theta), gain, style, lw=2,
                        label="φ={0:.0f}°".format(phi))
                if theta.max() <= 180.0:
                    ax.plot(-np.deg2rad(theta), gain, style, lw=1, alpha=0.6)
            ax.set_theta_zero_location("N")
            g, _, _ = ff.peak()
            ax.set_rmin(g - 40.0)
            ax.set_title("Radiation pattern (dBi) @ {0:.3f} GHz".format(ff.freq / 1e9),
                         fontsize=9)
            ax.legend(loc="lower left", fontsize=7)
        else:
            fig.text(0.5, 0.6, "No far-field data (enable ComputeFarField on the solver)",
                     ha="center", fontsize=9, color="#888888")
        if bom_rows:
            _multicol_table(fig, ["Item", "Detail", "Qty/Value"], bom_rows, 0.36)
        pdf.savefig(fig)
        _set_metadata(pdf, "EMStudio " + title, author)
    return path


# ---------------------------------------------------------------- magnetics report
def _fmt_freq(f):
    if f >= 1e9:
        return "{0:.4g} GHz".format(f / 1e9)
    if f >= 1e6:
        return "{0:.4g} MHz".format(f / 1e6)
    if f >= 1e3:
        return "{0:.4g} kHz".format(f / 1e3)
    return "{0:.4g} Hz".format(f)


def _draw_axi_geometry(ax, bodies):
    """Schematic r-z cross-section, mirrored about the axis (coil vs conductor)."""
    from matplotlib.patches import Patch

    for b in bodies:
        r0, r1, z0, z1 = b["r0"], b["r1"], b["z0"], b["z1"]
        color = "#2b8cff" if b.get("is_coil") else "#c87533"
        for x in (r0, -r1):  # right side, then mirror
            ax.add_patch(MplRect((x, z0), r1 - r0, z1 - z0, facecolor=color,
                                 edgecolor="#222222", lw=0.8, alpha=0.75))
        ax.text(0.5 * (r0 + r1), z1, b["name"], fontsize=6.5, ha="center",
                va="bottom", color="#222222")
    ax.axvline(0.0, ls="--", lw=0.8, color="#888888")
    r_max = max(b["r1"] for b in bodies)
    z_lo = min(b["z0"] for b in bodies)
    z_hi = max(b["z1"] for b in bodies)
    m = 0.15 * max(2 * r_max, z_hi - z_lo) + 1e-9
    ax.set_xlim(-r_max - m, r_max + m)
    ax.set_ylim(z_lo - m, z_hi + m)
    ax.set_aspect("equal")
    ax.set_xlabel("r (mm)  — mirrored about the axis", fontsize=8)
    ax.set_ylabel("z (mm)", fontsize=8)
    ax.legend(handles=[Patch(facecolor="#2b8cff", label="coil (driven)"),
                       Patch(facecolor="#c87533", label="conductor")],
              fontsize=7, loc="upper right")


def _draw_field_map(ax, vtu_path, freq_hz, bodies):
    """|B| amplitude in the r-z plane from the solved VTU (raises if unreadable)."""
    import matplotlib.tri as mtri

    from emstudio.solvers.elmer import parser

    mesh = parser.parse_vtu(vtu_path)
    pts = mesh["points"]
    br = mesh["point_data"].get("magnetic flux density re")
    bi = mesh["point_data"].get("magnetic flux density im")
    if br is None or bi is None:
        raise ValueError("no magnetic flux density in VTU")
    # phasor amplitude of the field vector, in mT
    bmag = np.sqrt(br[:, 0] ** 2 + br[:, 1] ** 2 + bi[:, 0] ** 2 + bi[:, 1] ** 2) * 1e3
    r_max = max(b["r1"] for b in bodies) * 1.6
    z_lo = min(b["z0"] for b in bodies)
    z_hi = max(b["z1"] for b in bodies)
    zc = 0.5 * (z_lo + z_hi)
    zh = max(0.5 * (z_hi - z_lo), r_max * 0.5) * 1.4
    view = (pts[:, 0] <= r_max) & (pts[:, 1] >= zc - zh) & (pts[:, 1] <= zc + zh)
    vmax = float(np.percentile(bmag[view], 97)) if view.any() else float(bmag.max())
    vmax = max(vmax, 1e-6)
    triang = mtri.Triangulation(pts[:, 0], pts[:, 1], mesh["triangles"])
    tcf = ax.tricontourf(triang, bmag, levels=np.linspace(0, vmax, 24),
                         cmap="magma", extend="max")
    ax.figure.colorbar(tcf, ax=ax, label="|B| amplitude (mT)", shrink=0.8)
    for b in bodies:
        ax.add_patch(MplRect((b["r0"], b["z0"]), b["r1"] - b["r0"], b["z1"] - b["z0"],
                             fill=False, lw=1.0,
                             edgecolor="#66ccff" if b.get("is_coil") else "#00e0a0"))
    ax.set_xlim(0, r_max)
    ax.set_ylim(zc - zh, zc + zh)
    ax.set_aspect("equal")
    ax.set_xlabel("r (mm)", fontsize=8)
    ax.set_ylabel("z (mm)", fontsize=8)
    ax.set_title("Magnetic flux density @ {0}".format(_fmt_freq(freq_hz)), fontsize=9)


def magnetics_report(result, path, title="Magnetics Analysis", project="", author=""):
    """Write an induction-heating / WPT magnetics report PDF. Returns the path.

    Adapts to the analysis: induction runs get power / temperature / coil
    impedance; WPT runs get the L/M/k coupling table. A field map is drawn
    from the solved VTU when available (gracefully omitted otherwise).
    """
    sweeps = result.sweep_cases()
    lmat = result.inductance_matrix()
    ks = result.coupling_k()
    bodies = result.bodies
    c0 = sweeps[0] if sweeps else None
    freqs = result.freqs_hz()
    heating = result.heating_curve()
    has_curve = len(sweeps) >= 3
    n_pages = 2 + (1 if (has_curve or heating) else 0)

    with PdfPages(path) as pdf:
        # --- page 1: summary + geometry ---
        fig = _new_page()
        _header(fig, title, result.meta.get("analysis", ""), 1, n_pages)
        rows = [
            ("Project", project or "—"),
            ("Prepared by", author or "—"),
            ("Solver", "{0} ({1})".format(
                result.meta.get("backend", "Elmer"),
                "general 3-D magnetostatic FEM (WhitneyAV)"
                if result.meta.get("mode3d") else
                "axisymmetric static DC FEM" if result.meta.get("static")
                else "axisymmetric harmonic FEM")),
        ]
        if freqs:
            rows.append(("Frequency", _fmt_freq(freqs[0]) if len(freqs) == 1
                         else "{0} – {1}, {2} points".format(
                             _fmt_freq(freqs[0]), _fmt_freq(freqs[-1]), len(freqs))))
        if c0 and c0["eddy_power_w"] > 0:
            rows.append(("Total eddy/Joule power", "{0:.4g} W @ {1}".format(
                c0["eddy_power_w"], _fmt_freq(c0["freq_hz"]))))
        if c0 and (c0.get("temperature")):
            tmax = max(t["t_max"] for t in c0["temperature"].values())
            rows.append(("Peak temperature", "{0:.1f} K  ({1:.0f} °C)".format(
                tmax, tmax - 273.15)))
        for (ni, nj), k in sorted(ks.items()):
            rows.append(("Coupling k ({0} <-> {1})".format(ni, nj),
                         "{0:.4g}".format(k)))
        _table(fig, rows, y0=0.88, title="Summary")

        ax = fig.add_axes([0.12, 0.09, 0.78, 0.44])
        if bodies and all("r0" in b for b in bodies):
            _draw_axi_geometry(ax, bodies)
            ax.set_title("Axisymmetric cross-section (r–z)", fontsize=9)
        else:
            fig.delaxes(ax)
            fig.text(0.5, 0.3, "(geometry unavailable)", ha="center",
                     fontsize=9, color="#888888")
        pdf.savefig(fig)

        # --- page 2: field map + result/BOM tables ---
        fig = _new_page()
        _header(fig, title + " — Fields & Bill of Materials",
                result.meta.get("analysis", ""), 2, n_pages)
        drew_field = False
        if c0 and bodies and all("r0" in b for b in bodies):
            ax = fig.add_axes([0.14, 0.52, 0.72, 0.33])
            try:
                _draw_field_map(ax, c0["vtu"], c0["freq_hz"], bodies)
                drew_field = True
            except Exception:  # noqa: BLE001 — field map is best-effort
                fig.delaxes(ax)
        if not drew_field:
            fig.text(0.5, 0.70, "(field map unavailable — VTU not found)",
                     ha="center", fontsize=9, color="#888888")

        # bodies: materials + losses + temperature.
        # Per-body power is the nodal decomposition RESCALED so it sums to the
        # field-integrated total (c0["eddy_power_w"]) — the nodal integral gets
        # the split between bodies right but is a few % low in absolute scale
        # (skin-peak under-resolution), so this keeps the breakdown consistent
        # with the headline total instead of leaking a few W on a lone body.
        headers = ["Body", "Role", "σ [MS/m]", "μr", "k [W/mK]", "P [W]", "Tmax [K]"]
        power = c0["body_power_w"] if c0 else {}
        nodal_total = sum(power.values())
        pscale = (c0["eddy_power_w"] / nodal_total) if (c0 and nodal_total > 0) else 1.0
        temps = (c0.get("temperature") if c0 else None) or {}
        data_rows = []
        for b in bodies:
            t = temps.get(b["name"], {})
            p_disp = power.get(b["name"], 0.0) * pscale
            data_rows.append([
                b["name"],
                "coil" if b.get("is_coil") else "conductor",
                "{0:.3g}".format(b.get("sigma", 0.0) / 1e6) if b.get("sigma", 0) else "—",
                "{0:.3g}".format(b.get("mu_r", 1.0)),
                "{0:.3g}".format(b["k_th"]) if b.get("k_th") else "—",
                "{0:.4g}".format(p_disp) if power.get(b["name"]) else "—",
                "{0:.1f}".format(t["t_max"]) if t else "—",
            ])
        y = _multicol_table(fig, headers, data_rows, 0.48,
                            col_frac=(0.22, 0.16, 0.14, 0.10, 0.14, 0.12, 0.12))

        # coils: electrical (turns / current / L / reflected R at the first freq).
        # L is the true self-inductance from the coupling extraction when it ran
        # (WPT); otherwise the in-situ effective inductance from the all-coils
        # sweep (induction — the coil's inductance with the workpiece present).
        # Reflected R (eddy loss referred to the coil) is shown only when real.
        if result.coils and c0:
            y -= 0.02
            cheaders = ["Coil", "Turns", "I_peak [A]", "L [µH]", "R_refl [mΩ]"]
            crows = []
            for coil in result.coils:
                name = coil["name"]
                _, ls, rs = result.coil_impedance(name)
                # prefer the self-inductance from the coupling extraction (WPT);
                # else the operating-point L_eff (may be NaN for an undriven coil)
                l_h = lmat[(name, name)] if (name, name) in lmat else ls[0]
                l_txt = "{0:.4g}".format(l_h * 1e6) if not np.isnan(l_h) else "—"
                r_txt = ("{0:.4g}".format(rs[0] * 1e3)
                         if not np.isnan(rs[0]) and abs(rs[0]) > 1e-6 else "—")
                crows.append([
                    name, coil.get("turns", "—"),
                    "{0:.4g}".format(coil.get("current_a", 0.0)),
                    l_txt, r_txt,
                ])
            y = _multicol_table(fig, cheaders, crows, y,
                                col_frac=(0.24, 0.16, 0.20, 0.20, 0.20))

        # coupling matrix (WPT)
        if lmat:
            y -= 0.02
            mheaders = ["Pair", "L1 [µH]", "L2 [µH]", "M [µH]", "k"]
            mrows = []
            for (ni, nj), k in sorted(ks.items()):
                m_h = 0.5 * (lmat[(ni, nj)] + lmat[(nj, ni)])
                mrows.append([
                    "{0} <-> {1}".format(ni, nj),
                    "{0:.4g}".format(lmat[(ni, ni)] * 1e6),
                    "{0:.4g}".format(lmat[(nj, nj)] * 1e6),
                    "{0:.4g}".format(m_h * 1e6),
                    "{0:.4g}".format(k),
                ])
            _multicol_table(fig, mheaders, mrows, y,
                            col_frac=(0.28, 0.18, 0.18, 0.18, 0.18))
        pdf.savefig(fig)

        # --- page 3 (optional): heating curve and/or frequency-sweep curves ---
        if has_curve or heating:
            fig = _new_page()
            sub = "Heating Curve" if heating else "Frequency Sweep"
            _header(fig, title + " — " + sub, result.meta.get("analysis", ""),
                    3, n_pages)
            if heating:
                t, temp = heating
                ax0 = fig.add_axes([0.12, 0.55, 0.78, 0.34])
                ax0.plot(np.array(t), np.array(temp) - 273.15, "-o", lw=2, ms=3)
                ax0.set_xlabel("time (s)", fontsize=8)
                ax0.set_ylabel("max temperature (°C)", fontsize=8)
                ax0.grid(True, alpha=0.4)
                ax0.set_title("Transient heating curve (workpiece hottest point)",
                              fontsize=9)
            elif has_curve:
                fhz = np.array(result.freqs_hz())
                ax1 = fig.add_axes([0.12, 0.55, 0.78, 0.34])
                ax1.semilogx(fhz, np.array(result.eddy_power_w()), "-o", lw=2, ms=3)
                ax1.set_ylabel("Eddy/Joule power (W)", fontsize=8)
                ax1.grid(True, which="both", alpha=0.4)
                ax1.set_title("Dissipated power vs frequency", fontsize=9)
                if result.coils:
                    ax2 = fig.add_axes([0.12, 0.10, 0.78, 0.34])
                    for coil in result.coils:
                        cf, ls, _ = result.coil_impedance(coil["name"])
                        ax2.semilogx(cf, np.array(ls) * 1e6, "-", lw=2,
                                     label="L {0}".format(coil["name"]))
                    ax2.set_xlabel("Frequency (Hz)", fontsize=8)
                    ax2.set_ylabel("L_eff (µH)", fontsize=8)
                    ax2.grid(True, which="both", alpha=0.4)
                    ax2.legend(fontsize=7)
            pdf.savefig(fig)

        _set_metadata(pdf, "EMStudio " + title, author)
    return path


# ---------------------------------------------------------------- element report
def _element_summary_rows(family, design):
    """Per-family key/value rows for the element-design summary table."""
    d = design
    if family == "yagi":
        return [
            ("Family", "Yagi-Uda (NBS TN-688)"),
            ("Design frequency", _fmt_freq(d.get("f0_hz", 0.0))),
            ("Boom class", "{0:g} lambda ({1:.4g} m)".format(
                d.get("boom_lambda", 0.0), d.get("boom_length_m", 0.0))),
            ("Elements", "{0} (reflector + driven + {1} directors)".format(
                d.get("n_elements", 0), d.get("n_directors", 0))),
            ("Gain (NBS measured)", "{0:.2f} dBi = {1:.2f} dBd".format(
                d.get("gain_dbi", 0.0), d.get("gain_dbd", 0.0))),
            ("Driven feed R", "~{0:.0f} ohm (folded: ~{1:.0f} ohm)".format(
                d.get("driven_feed_r_ohm", 0.0),
                d.get("folded_driven_feed_r_ohm", 0.0))),
            ("d/lambda", "{0:.4f}".format(d.get("d_over_lambda", 0.0))),
        ]
    if family == "patch":
        return [
            ("Family", "Microstrip patch (TL synthesis)"),
            ("Design frequency", _fmt_freq(d.get("f0_hz", 0.0))),
            ("Substrate", "er {0:g}, h {1:.3g} mm".format(
                d.get("er", 0.0), d.get("h_m", 0.0) * 1e3)),
            ("Patch W x L", "{0:.2f} x {1:.2f} mm".format(
                d.get("width_m", 0.0) * 1e3, d.get("length_m", 0.0) * 1e3)),
            ("Effective permittivity", "{0:.4f}".format(d.get("er_eff", 0.0))),
            ("Edge resistance", "{0:.0f} ohm (two-slot estimate)".format(
                d.get("edge_resistance_ohm", 0.0))),
            ("Feed offset (probe)", "{0:.2f} mm for {1:.0f} ohm".format(
                d.get("feed_offset_m", 0.0) * 1e3, d.get("target_z_ohm", 0.0))),
            ("Gain (estimate)", "{0:.2f} dBi = {1:.2f} dBd".format(
                d.get("gain_dbi", 0.0), d.get("gain_dbd", 0.0))),
        ]
    if family == "lpda":
        return [
            ("Family", "LPDA (Carrel log-periodic)"),
            ("Band", "{0} - {1}  (B = {2:.3g})".format(
                _fmt_freq(d.get("f_lo_hz", 0.0)), _fmt_freq(d.get("f_hi_hz", 0.0)),
                d.get("bandwidth", 0.0))),
            ("tau / sigma", "{0:.3f} / {1:.3f}{2}".format(
                d.get("tau", 0.0), d.get("sigma", 0.0),
                " (optimum line)" if d.get("on_optimum_sigma") else "")),
            ("Apex half-angle", "{0:.1f} deg".format(d.get("alpha_deg", 0.0))),
            ("Elements", "{0} (N_exact {1:.2f})".format(
                d.get("n_elements", 0), d.get("n_exact", 0.0))),
            ("Boom length", "{0:.4g} m".format(d.get("boom_length_m", 0.0))),
            ("Feeder Z0 (crossed)", "{0:.1f} ohm for R0 ~ {1:.0f} ohm".format(
                d.get("feeder_z0_ohm", 0.0), d.get("r0_ohm", 0.0))),
            ("Gain (corrected contours)", "{0:.2f} dBi = {1:.2f} dBd".format(
                d.get("gain_dbi", 0.0), d.get("gain_dbd", 0.0))),
        ]
    # wire family (dipole / monopole / folded / lambda-fraction)
    length_m = d.get("length_m", 0.0)
    length_ft = d.get("length_ft") or length_m / 0.3048
    edited = " (user-edited)" if d.get("edited") else ""
    r = d.get("feed_r_ohm")
    x = d.get("feed_x_ohm")
    if r is None:
        # lambda-fraction rows: not resonant by design — no single feed Z
        feed = "not resonant by design — see the notes (matching is §7)"
    else:
        feed = "{0:.1f} {1} j{2:.1f} ohm".format(
            r, "+" if (x or 0.0) >= 0 else "-", abs(x or 0.0))
    return [
        ("Family", "Wire ({0})".format(d.get("kind", "dipole"))),
        ("Design frequency", _fmt_freq(d.get("f0_hz", 0.0))),
        ("Length", "{0:.4f} m ({1:.3f} ft){2}".format(
            length_m, length_ft, edited)),
        ("End-effect K", "{0:.4f}".format(d.get("k_factor", 0.0))),
        ("Feed impedance", feed),
        ("Gain", "{0:.2f} dBi = {1:.2f} dBd".format(
            d.get("gain_dbi", 0.0), d.get("gain_dbd", 0.0))),
    ]


def _element_schedule(family, design):
    """(headers, rows, col_frac) for the build-schedule table."""
    d = design
    if family == "yagi":
        rows = [(e["name"], "{0:.4f}".format(e["position_m"]),
                 "{0:.4f}".format(e["length_m"]),
                 "{0:.4f}".format(e.get("cut_length_m", e["length_m"])))
                for e in d.get("elements", [])]
        return (["Element", "Position (m)", "L wire (m)", "L cut (m)"],
                rows, [0.34, 0.22, 0.22, 0.22])
    if family == "patch":
        rows = [
            ("Patch width W", "{0:.3f} mm".format(d.get("width_m", 0.0) * 1e3)),
            ("Patch length L", "{0:.3f} mm".format(d.get("length_m", 0.0) * 1e3)),
            ("Substrate height h", "{0:.3f} mm".format(d.get("h_m", 0.0) * 1e3)),
            ("Fringing extension dL", "{0:.3f} mm".format(
                d.get("delta_l_m", 0.0) * 1e3)),
            ("Probe feed offset from centre", "{0:.3f} mm".format(
                d.get("feed_offset_m", 0.0) * 1e3)),
        ]
        return (["Dimension", "Value"], rows, [0.55, 0.45])
    if family == "lpda":
        rows = [(e["name"] + (" (fed)" if e.get("kind") == "fed" else ""),
                 "{0:.4f}".format(e["position_m"]),
                 "{0:.4f}".format(e["length_m"]))
                for e in d.get("elements", [])]
        return (["Element", "Position (m)", "Length (m)"],
                rows, [0.40, 0.30, 0.30])
    rows = [("{0} element".format(d.get("kind", "dipole")),
             "{0:.4f} m".format(d.get("length_m", 0.0)))]
    return (["Item", "Length"], rows, [0.55, 0.45])


def _draw_element_schematic(ax, family, design):
    """Simple dimensioned build sketch per family (report-grade, not the
    dialog's interactive one)."""
    d = design
    ax.set_aspect("equal")
    ax.axis("off")
    if family in ("yagi", "lpda"):
        els = d.get("elements", [])
        if not els:
            return
        xs = [e["position_m"] for e in els]
        maxlen = max(e["length_m"] for e in els)
        span = max(max(xs) - min(xs), 1e-9)
        ax.plot([min(xs), max(xs)], [0, 0], "-", color="#666666", lw=2)
        key = "driven" if family == "yagi" else "fed"
        for e in els:
            half = e["length_m"] / 2.0
            color = "#d33333" if e.get("kind") == key else "#c87533"
            ax.plot([e["position_m"], e["position_m"]], [-half, half], "-",
                    color=color, lw=2)
            if e.get("kind") == key:
                ax.plot([e["position_m"]], [0], "o", color="#d33333", ms=4)
        ax.annotate("", xy=(max(xs), -maxlen * 0.62),
                    xytext=(min(xs), -maxlen * 0.62),
                    arrowprops=dict(arrowstyle="<->", color="#2b8cff"))
        ax.text((min(xs) + max(xs)) / 2.0, -maxlen * 0.75,
                "boom {0:.4g} m".format(d.get("boom_length_m", span)),
                ha="center", color="#2b8cff", fontsize=8)
        ax.set_xlim(min(xs) - 0.08 * span, max(xs) + 0.12 * span)
        ax.set_ylim(-maxlen * 0.95, maxlen * 0.72)
        return
    if family == "patch":
        w = d.get("width_m", 0.0) * 1e3
        length = d.get("length_m", 0.0) * 1e3
        off = d.get("feed_offset_m", 0.0) * 1e3
        ax.add_patch(MplRect((-length / 2, -w / 2), length, w,
                             facecolor="#c87533", alpha=0.6,
                             edgecolor="#7a4a1e"))
        ax.plot([off], [0], "o", color="#d33333", ms=5)
        ax.annotate("", xy=(length / 2, -w * 0.62), xytext=(-length / 2, -w * 0.62),
                    arrowprops=dict(arrowstyle="<->", color="#2b8cff"))
        ax.text(0, -w * 0.72, "L = {0:.2f} mm (resonant)".format(length),
                ha="center", fontsize=8, color="#2b8cff")
        ax.annotate("", xy=(length * 0.62, w / 2), xytext=(length * 0.62, -w / 2),
                    arrowprops=dict(arrowstyle="<->", color="#2b8cff"))
        ax.text(length * 0.72, 0, "W = {0:.2f} mm".format(w), rotation=90,
                va="center", fontsize=8, color="#2b8cff")
        ax.text(off, w * 0.10, "feed", fontsize=7, ha="center", color="#d33333")
        ax.set_xlim(-length * 0.85, length * 0.95)
        ax.set_ylim(-w * 0.9, w * 0.8)
        return
    # wire family: a vertical element with a length dimension. Dipole/folded
    # are center-fed free-standing; monopole AND the lambda-fraction
    # verticals are BASE-fed over ground (the dialog sketch convention)
    length = d.get("length_m", 0.0) or 1e-9
    grounded = d.get("kind") not in ("dipole", "folded")
    ax.plot([0, 0], [0, length], "-", color="#c87533", lw=3)
    feed_y = 0.0 if grounded else length / 2.0
    ax.plot([0], [feed_y], "o", color="#d33333", ms=5)
    ax.annotate("", xy=(length * 0.12, length), xytext=(length * 0.12, 0),
                arrowprops=dict(arrowstyle="<->", color="#2b8cff"))
    ax.text(length * 0.16, length / 2.0,
            "{0:.4f} m".format(length), rotation=90, va="center",
            fontsize=8, color="#2b8cff")
    if grounded:
        ax.plot([-length * 0.15, length * 0.3], [0, 0], "-", color="#555555",
                lw=1.5)
        ax.text(length * 0.22, -length * 0.05, "ground", fontsize=7,
                color="#555555")
    ax.set_xlim(-length * 0.3, length * 0.5)
    ax.set_ylim(-length * 0.12, length * 1.1)


def element_report(design, path, family=None, title="Element Design",
                   project="", author=""):
    """Write an Element Designer build report (summary + schedule + sketch).

    ``design`` is an engine design dict (``wire_elements``/``yagi``/
    ``patch_tl``/``lpda``); ``family`` overrides/supplies ``design['family']``
    (the wire engines don't tag one). Returns the path.
    """
    fam = family or design.get("family") or "wire"
    with PdfPages(path) as pdf:
        # page 1: summary
        fig = _new_page()
        _header(fig, title, project, 1, 2)
        y = _table(fig, _element_summary_rows(fam, design), y0=0.87,
                   title="Design summary")
        warnings = list(design.get("warnings", []) or [])
        if warnings:
            fig.text(0.10, y - 0.012, "Notes & caveats", fontsize=11,
                     fontweight="bold")
            y -= 0.042
            import textwrap

            for w in warnings:
                for ln in textwrap.wrap("- " + str(w), 96):
                    fig.text(0.10, y, ln, fontsize=7.5, color="#444444")
                    y -= 0.016
                y -= 0.004
        src = design.get("source_note", "")
        if src:
            import textwrap

            y -= 0.010
            for ln in textwrap.wrap("Source: " + str(src), 100):
                fig.text(0.10, y, ln, fontsize=7, color="#777777")
                y -= 0.014
        pdf.savefig(fig)

        # page 2: build sketch + schedule. The schedule area fits ~22 rows;
        # longer schedules (an LPDA can reach n_max = 40 elements) split into
        # two side-by-side blocks so no row ever slides off the page.
        fig = _new_page()
        _header(fig, title, project, 2, 2)
        ax = fig.add_axes([0.10, 0.52, 0.80, 0.36])
        _draw_element_schematic(ax, fam, design)
        headers, rows, frac = _element_schedule(fam, design)
        max_rows = 22
        if len(rows) <= max_rows:
            _multicol_table(fig, headers, rows, y0=0.46, col_frac=frac)
        else:
            split = (len(rows) + 1) // 2
            if split > max_rows:  # hard guard (>44 rows cannot happen today)
                rows = rows[:2 * max_rows - 1] + [
                    tuple(["…"] * len(headers))]
                split = max_rows
            _multicol_table(fig, headers, rows[:split], y0=0.46,
                            x0=0.06, width=0.42, col_frac=frac)
            _multicol_table(fig, headers, rows[split:], y0=0.46,
                            x0=0.54, width=0.42, col_frac=frac)
        pdf.savefig(fig)

        _set_metadata(pdf, "EMStudio " + title, author)
    return path


def _set_metadata(pdf, title, author):
    d = pdf.infodict()
    d["Title"] = title
    d["Author"] = author or "EMStudio"
    d["Creator"] = "EMStudio (FreeCAD workbench)"


# ------------------------------------------------------- system matching report
def _matching_ref_z0(design):
    """The system reference the match is measured against = Re(z_source)."""
    zs = design.get("z_source", complex(50.0, 0.0))
    return design.get("z0") or (complex(zs).real if zs else 50.0)


def _matching_summary_rows(design, q_ind=None, q_cap=None):
    from emstudio.system import matching as _M

    f0 = design["match_freq_hz"]
    zs = complex(design.get("z_source", complex(50.0)))
    zl = complex(design.get("z_load", complex(50.0)))
    z0 = _matching_ref_z0(design)
    ev = _M.evaluate(design.get("elements", []), zs, zl, [f0], z0=z0, f0_hz=f0)
    il = _M.estimate_insertion_loss_db(design, q_ind=q_ind, q_cap=q_cap)
    rows = [
        ("Topology", design.get("name", design.get("kind", "?"))),
        ("Source / system Z0", "{0:.3g} ohm".format(z0)),
        ("Element (load) Z", "{0:.4g}{1:+.4g}j ohm".format(zl.real, zl.imag)),
        ("Design frequency", _fmt_freq(f0)),
    ]
    if design.get("q_network") is not None:
        rows.append(("Network Q", "{0:.3g}".format(design["q_network"])))
    if design.get("q_loaded") is not None:
        rows.append(("Loaded Q (chosen)", "{0:.3g}".format(design["q_loaded"])))
    rows += [
        ("Predicted VSWR @ f0", "{0:.3f}".format(ev["vswr"][0])),
        ("Predicted return loss @ f0", "{0:.1f} dB".format(ev["return_loss_db"][0])),
        ("Est. insertion loss",
         "{0:.3f} dB{1}".format(il, "" if (q_ind or q_cap) else " (ideal parts)")),
    ]
    return rows


def _matching_schedule(design):
    """(headers, rows, col_frac) for the component / section schedule."""
    kind = design.get("kind")
    comps = design.get("components") or []
    if comps:
        headers = ("Arm", "Type", "Value", "Reactance")
        rows = [(c["arm"], c["type"], c.get("display", ""),
                 "{0:.1f} ohm".format(c["reactance_ohm"])
                 if c.get("reactance_ohm") is not None else "")
                for c in comps]
        return headers, rows, (0.20, 0.28, 0.28, 0.24)
    if kind in ("quarter_wave", "binomial"):
        zs = design.get("section_impedances", [])
        headers = ("Section", "Zc (ohm)", "Electrical length")
        rows = [("{0}".format(i + 1), "{0:.2f}".format(z), "lambda/4 @ f0")
                for i, z in enumerate(zs)]
        return headers, rows, (0.25, 0.40, 0.35)
    if kind == "single_stub":
        headers = ("Element", "Length (lambda)", "Note")
        rows = [("line to stub", "{0:.4f}".format(design.get("d_lambda", 0)),
                 "series line, Z0"),
                ("{0} stub".format(design.get("stub", "open")),
                 "{0:.4f}".format(design.get("l_lambda", 0)), "shunt stub, Z0")]
        return headers, rows, (0.30, 0.30, 0.40)
    return ("Item", "Value"), [("(no schedule)", "")], (0.5, 0.5)


def _draw_matching_schematic(ax, design):
    """A simple source -> [network boxes] -> load ladder diagram."""
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 4)
    ax.axis("off")
    zs = complex(design.get("z_source", complex(50.0)))
    zl = complex(design.get("z_load", complex(50.0)))
    ax.text(0.4, 2.0, "Source\n{0:.0f} ohm".format(zs.real), ha="center",
            va="center", fontsize=8,
            bbox=dict(boxstyle="round", fc="#dfe8f4", ec="#2b8cff"))
    ax.text(9.6, 2.0, "Element\n{0:.0f}{1:+.0f}j".format(zl.real, zl.imag),
            ha="center", va="center", fontsize=8,
            bbox=dict(boxstyle="round", fc="#f4e8df", ec="#d38b2b"))
    els = design.get("elements", [])
    n = max(len(els), 1)
    span = 8.0
    for i, el in enumerate(els):
        x = 1.4 + span * (i + 0.5) / n
        kind = el.get("kind")
        if kind in ("L", "C"):
            label = "{0}\n{1}".format(el["arm"],
                                      "L" if kind == "L" else "C")
        elif kind == "tline":
            label = "line\nZc={0:.0f}".format(el.get("zc_ohm", 0))
        elif kind == "stub":
            label = "{0}\nstub".format(el.get("termination", ""))
        else:
            label = kind or "?"
        ax.text(x, 2.0, label, ha="center", va="center", fontsize=7,
                bbox=dict(boxstyle="round", fc="#eef", ec="#446"))
    ax.plot([0.8, 9.2], [2.0, 2.0], color="#446", lw=0.8, zorder=0)


def matching_report(design, path, title="Matching Network", project="",
                    author="", q_ind=None, q_cap=None):
    """Write a §7 matching-network design report (summary + predicted curves +
    component schedule + schematic). ``design`` is a
    :mod:`emstudio.system.matching` design dict. Returns the path.

    Optional ``q_ind``/``q_cap`` give component quality factors so the report's
    insertion-loss figure reflects real (lossy) parts."""
    from emstudio.system import matching as _M

    f0 = design["match_freq_hz"]
    zs = complex(design.get("z_source", complex(50.0)))
    zl = complex(design.get("z_load", complex(50.0)))
    z0 = _matching_ref_z0(design)
    with PdfPages(path) as pdf:
        # page 1: summary + predicted VSWR / return-loss curves
        fig = _new_page()
        _header(fig, title, project, 1, 2)
        y = _table(fig, _matching_summary_rows(design, q_ind, q_cap), y0=0.87,
                   title="Matching summary")
        notes = list(design.get("warnings", []) or []) + \
            list(design.get("notes", []) or [])
        if notes:
            import textwrap
            fig.text(0.10, y - 0.010, "Notes & caveats", fontsize=11,
                     fontweight="bold")
            y -= 0.040
            for w in notes:
                for ln in textwrap.wrap("- " + str(w), 96):
                    fig.text(0.10, y, ln, fontsize=7.5, color="#444444")
                    y -= 0.016
                y -= 0.003
        # predicted curves (live matplotlib axes, per the house furniture)
        span = [f0 * (0.5 + 1.0 * k / 120.0) for k in range(121)]
        ev = _M.evaluate(design.get("elements", []), zs, zl, span, z0=z0, f0_hz=f0)
        ax = fig.add_axes([0.12, 0.10, 0.76, 0.26])
        fmhz = [f / 1e6 for f in span]
        ax.plot(fmhz, ev["vswr"], color="#2b8cff", label="VSWR")
        ax.set_xlabel("Frequency (MHz)", fontsize=8)
        ax.set_ylabel("VSWR", fontsize=8, color="#2b8cff")
        ax.tick_params(labelsize=7)
        ax.axvline(f0 / 1e6, color="#888", ls=":", lw=0.8)
        ax.set_title("Predicted match vs frequency", fontsize=9)
        ax2 = ax.twinx()
        ax2.plot(fmhz, ev["return_loss_db"], color="#d38b2b", label="Return loss")
        ax2.set_ylabel("Return loss (dB)", fontsize=8, color="#d38b2b")
        ax2.tick_params(labelsize=7)
        pdf.savefig(fig)

        # page 2: schematic + component / section schedule
        fig = _new_page()
        _header(fig, title, project, 2, 2)
        ax = fig.add_axes([0.08, 0.56, 0.84, 0.32])
        _draw_matching_schematic(ax, design)
        fig.text(0.10, 0.50, "Component schedule", fontsize=11,
                 fontweight="bold")
        headers, rows, frac = _matching_schedule(design)
        _multicol_table(fig, headers, rows[:22], y0=0.46, col_frac=frac)
        pdf.savefig(fig)

        _set_metadata(pdf, "EMStudio " + title, author)
    return path
